APP_PLATFORM := ${APP_PLATFORM}
APP_ABI := ${TARGET_ABI}
APP_STL := ${APP_STL}
APP_MODULES := Irrlicht

APP_CFLAGS   := ${TARGET_CFLAGS_ADDON}
APP_CXXFLAGS := ${TARGET_CPPFLAGS_ADDON} -std=gnu++17
APP_CPPFLAGS := ${TARGET_CPPFLAGS_ADDON} -DNO_IRR_COMPILE_WITH_SDL_TEXTINPUT_
